### ISSUE TITLE
a problem about loading pasta checkpoints

### ISSUE THREAD

**Issue by tom68-ll** [ruc-datalab/PASTA#1]
Hello Author，
Thank you very much for your excellent work.  But we encountered a problem when loading the pasta checkpoint as described in the readme. The problem always seems to be in the following sections：

https://github.com/ruc-datalab/PASTA/blob/2f5e91089cc24f93a45172bcda7d61672711cd13/src/utils/dataset.py#L16

Looking forward to your recovery！

**Comment by zihuig** [comment]
Hello @tom68-ll ,
Thank you for your attention to our work. I have also encountered this issue when loading the DeBERTaV3 model locally, and here are two simple solutions:

1. Due to the fact that PASTA pre-training does not change the original tokenizer, you can set the `tokenizer_path` to `microsoft/deberta-v3-large`, which can be directly downloaded from the huggingface to avoid this issue.

2. You can specify the vocab_file like `vocab_file = 'your_local_pasta_model_path/' + 'spam.model'`under line 136 of the  file `site-packages/transformers/models/deberta_v2/tokenization_deberta_v2.py`.

**Comment by tom68-ll** [comment]
Thank you very much for your answer！We have tried both of these approaches, but there are still problems：

1. I have tried the first solution above before and although the model works, it doesn't seem to be working as desired (the results are only about 50% random)
2. In the second solution, we still use the original PASTA configuration script， and added` vocab_file = 'your_local_pasta_model_path/' + 'spam.model'` to line 136 of the file `site-packages/transformers/models/deberta_v2/tokenization_deberta_v2.py`, as follows：
 ```
super().__init__(
            do_lower_case=do_lower_case,
            bos_token=bos_token,
            eos_token=eos_token,
            unk_token=unk_token,
            sep_token=sep_token,
            pad_token=pad_token,
            cls_token=cls_token,
            mask_token=mask_token,
            split_by_punct=split_by_punct,
            sp_model_kwargs=self.sp_model_kwargs,
            vocab_file='/XXXXX/PASTA/pasta/spam.model',
            **kwargs,
        )
```
But we still got the error：
```
Traceback (most recent call last):
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/XXX/.vscode-server/extensions/ms-python.python-2022.8.0/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/XXX/.vscode-server/extensions/ms-python.python-2022.8.0/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/XXX/.vscode-server/extensions/ms-python.python-2022.8.0/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/XXX/PASTA/src/run_finetune.py", line 151, in <module>
    Trainer = TabFV_Trainer(
  File "/XXX/PASTA/src/run_finetune.py", line 34, in __init__
    self.dt = DataManager(data_args)
  File "/XXX/PASTA/src/utils/dataset.py", line 19, in __init__
    self.tokenizer = DebertaV2Tokenizer.from_pretrained(data_args.tokenizer_path)
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1788, in from_pretrained
    return cls._from_pretrained(
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1923, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/site-packages/transformers/models/deberta_v2/tokenization_deberta_v2.py", line 139, in __init__
    if not os.path.isfile(vocab_file):
  File "/XXX/miniconda3/envs/pasta/lib/python3.8/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
I hope to get your guidance, thanks again!

**Comment by zihuig** [comment]
It seems that the `vocab_file` has not been set correctly. Please place `vocab_file='/XXXXX/spam.model'` above `if not os.path.isfile(vocab_file):`, like this:
```sh
        super().__init__(
            do_lower_case=do_lower_case,
            bos_token=bos_token,
            eos_token=eos_token,
            unk_token=unk_token,
            sep_token=sep_token,
            pad_token=pad_token,
            cls_token=cls_token,
            mask_token=mask_token,
            split_by_punct=split_by_punct,
            sp_model_kwargs=self.sp_model_kwargs,
            **kwargs,
        )

        vocab_file='/XXXXX/spam.model' # change it to your local path
        if not os.path.isfile(vocab_file):
            raise ValueError(
                f"Can't find a vocabulary file at path '{vocab_file}'. To load the vocabulary from a Google pretrained "
                "model use `tokenizer = AutoTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`"
            )
```
Furthermore, if you directly test the pre-trained [PASTA model](https://drive.google.com/drive/folders/1sqZt8Wu7PQ3ha4260E7Gcq4WipKj6LD8) on the TabFact test set, the result is indeed 50%, as this model has not been fine-tuned on the TabFact train set. The fine-tuned model is this [link](https://drive.google.com/file/d/1cUq1G9Mx_gNwmNsptBEnRaVor8c70sE2/view). You can use it by adding `"load_checkpoints": "/save_checkpoints/tabfact.pkl"` in your .config file.

**Comment by tom68-ll** [comment]
Thanks so much for your patience!

**Comment by Heaven-zhw** [comment]
> Hello @tom68-ll , Thank you for your attention to our work. I have also encountered this issue when loading the DeBERTaV3 model locally, and here are two simple solutions:
> 
> 1. Due to the fact that PASTA pre-training does not change the original tokenizer, you can set the `tokenizer_path` to `microsoft/deberta-v3-large`, which can be directly downloaded from the huggingface to avoid this issue.
> 2. You can specify the vocab_file like `vocab_file = 'your_local_pasta_model_path/' + 'spam.model'`under line 136 of the  file `site-packages/transformers/models/deberta_v2/tokenization_deberta_v2.py`.

Hello, I find in microsoft/deberta-v3-large the tokenizer model file is "spm.model", but in PASTA the model file is "spam.model". Maybe you can rename the "spam.model" to "spm.model" to solve this problem.

**Comment by tom68-ll** [comment]
Thank you very much for your enthusiastic response.
